name: BranchWorkflow

on:
  push:
    branches-ignore: [main]

jobs:
  test:
    name: TestStage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get install -y libatomic1

      - name: Build + Test
        run: make
